services:
  postgres:
    image: postgres:15
    container_name: postgres-springboot2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: 01DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
